version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_USER=massage
      - POSTGRES_PASSWORD=massage
      - POSTGRES_DB=massage
    ports:
      - '5232:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql